# Site settings
title:       The Serious Fox Labs
email:       your_email@example.com
author:      Serious Fox HQ
description: "Writings from the Serious Fox Team, makers of Matterhorn, Meta Trails and superb apps for our clients"
baseurl:     ""
url:         "/"

# Authors
authors:
  josh:
    name: Josh Crowder
    display_name: Josh
    email: josh@seriousfox.co.uk
    twitter: joshcrowder
    avatar: "http://gravatar.com/avatar/a6968fbfb11b00704757be49891ffb80.png"
  alex:
    name: Alex Handley
    display_name: Alex
    email: alex@seriousfox.co.uk
    twitter: alex_handley
    avatar: "http://gravatar.com/avatar/df4ba93d4df92bb3fa525a12c015a82b.png"
  linnea:
    name: Linnea Strid
    display_name: Linnea
    email: linnea@seriousfox.co.uk
    twitter: babolili
    avatar: "http://www.gravatar.com/avatar/698433e3653ae88d36854dc738b0afa6.png"
  marin:
    name: Marin Le Maignan
    display_name: Marin
    email: marin@seriousfox.co.uk
    twitter: seriousfoxhq
    avatar: "http://gravatar.com/avatar/95fdc8ca33fa2e3d7dacd35dcd1ae8a5.png"


# Google analytics
google_analytics: UA-44214769-6

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: seriousfox
stackoverflow_id:
twitter_username: seriousfoxhq
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
